### ISSUE TITLE
dostfilms.cc

### ISSUE THREAD

**Issue by XX-J** [AdguardTeam/AdguardFilters#25351]
[https://dostfilms.cc/publ/uzhasy/poka-nikto-ne-poranilsya-2018/5-1-0-6896](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://dostfilms.cc/publ/uzhasy/poka-nikto-ne-poranilsya-2018/5-1-0-6896)

 **1**. Стилевая защита от выделения (копирования) в [https://dostfilms.cc/templates/dostfilms/css/my.css](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://dostfilms.cc/templates/dostfilms/css/my.css):

```
 .zashitatekstov {
 -moz-user-select: none;
 -webkit-user-select: none;
 -ms-user-select: none;
 -o-user-select: none;
 user-select: none;
}

.zashitatekstov-dlya-fullstory {
 -moz-user-select: none;
 -webkit-user-select: none;
 -ms-user-select: none;
 -o-user-select: none;
 user-select: none;
}

.zashitatekstov897 {
 -moz-user-select: none;
 -webkit-user-select: none;
 -ms-user-select: none;
 -o-user-select: none;
 user-select: none;
}
```

 **2**. Отступ основной консоли сайта, связанный с рекламой: `dostfilms.cc#$#header { margin-top: auto!important; margin-bottom: auto!important; }`

<details><summary>Screenshot:</summary>

![2018 11 09-1](https://user-images.githubusercontent.com/17948007/48307306-21674200-e55b-11e8-8bf7-24b0774d57c4.png)
</details>

___________________________________________________
Mozilla Firefox v53.0.3 (Win7SP1) - Adguard v3.0.3
Английский фильтр | Русский фильтр | Фильтр раздражителей
Фильтр виджетов социальных сетей | Фильтр счетчиков и системы аналитики

**Comment by krystian3w** [comment]
```css
dostfilms.net#$#.zashitatekstov, .zashitatekstov-dlya-fullstory, .zashitatekstov897 { -moz-user-select: text !important;  -webkit-user-select: text !important; -ms-user-select: text !important; -o-user-select: text !important;  user-select: text !important; }
```
