### ISSUE TITLE
microsoft.com

### ISSUE THREAD

**Issue by adranger** [AdguardTeam/AdguardFilters#30044]
`https://www.microsoft.com/store/most-popular/apps/pc`

Mailing list overlay annoyance. If you don't see it right away, click on  `Netflix`.

![microsoft store](https://user-images.githubusercontent.com/35470489/53282635-37b79900-3719-11e9-8c6f-e0deebc33c9e.jpg)

Adguard Base + Annoyances + Portuguese + Russian + Social + Spyware
uBlock Origin 1.18.4
Firefox 65

**Comment by krystian3w** [comment]
```css
microsoft.com#$##email-newsletter-dialog { display : none!important; }
microsoft.com#$#body[style^="overflow: hidden;"] { overflow: visible!important; }
```
