### ISSUE TITLE
lexus-polska.pl/dealers

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/AdguardFilters#77681]
Cookie pop-ups on dealers pages:

```css
lexus-katowice.pl,lexus-krakow.com.pl,lexus-leszno.pl,lexus-lodz.pl,lexus-poznan.pl,lexus-szczecin.pl,lexus-trojmiasto.pl,lexus-warszawaradosc.pl,lexus-wroclaw.pl,lexuskrakow-zakopianska.pl,lexuswarszawa-pulawska.pl,lexuswarszawa-wola.pl,lexuswarszawa-zeran.pl#$#.ReactModal__Body--open { overflow-y: auto !important }
lexus-katowice.pl,lexus-krakow.com.pl,lexus-leszno.pl,lexus-lodz.pl,lexus-poznan.pl,lexus-szczecin.pl,lexus-trojmiasto.pl,lexus-warszawaradosc.pl,lexus-wroclaw.pl,lexuskrakow-zakopianska.pl,lexuswarszawa-pulawska.pl,lexuswarszawa-wola.pl,lexuswarszawa-zeran.pl#?##div.ReactModalPortal:has(div[class*="CookiesModal"])
```

maybe possible use `abort-current-inline-script` or `set-localStorage/sessionStorage` (in the future).

No tested pages in Alexa ranks to exlude "no visitors".
