### ISSUE TITLE
easypdf.com social popup

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdguardFilters#77859]
`https://easypdf.com/`

Proposed filters:
```
easypdf.com###social:not(body), .modal-backdrop
```

**Comment by krystian3w** [comment]
Need repair scroll:

```css
easypdf.com#$#.modal-open { overflow: visibile !important; }
easypdf.com#$#.modal-open[style*="padding"] { padding-right: 0 !important; }
easypdf.com#$##social.modal { display: none !important; }
easypdf.com#$##social.modal ~ .modal-backdrop { display: none !important; }
```

**Comment by krystian3w** [comment]
Also should works remove element from dom tree:

```css
easypdf.com#$##social.modal {remove: true }
easypdf.com$$#social.modal
```

if `abort-current-inline-script` is to slow or break to match with use `stack`.
